//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ctdonhang
    {
        public int mact { get; set; }
        public int madonhang { get; set; }
        public int masp { get; set; }
        public int soluong { get; set; }
    
        public virtual sanpham sanpham { get; set; }
        public virtual donhang donhang { get; set; }


    }
}
