//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class diachi
    {
        public int madiachi { get; set; }
        public string diachi1 { get; set; }
        public int matv { get; set; }
        public string loai { get; set; }
    
        public virtual thanhvien thanhvien { get; set; }
    }
}
