//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class donhang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public donhang()
        {
            this.ctdonhangs = new HashSet<ctdonhang>();
        }
    
        public int madonhang { get; set; }
        public Nullable<System.DateTime> ngaydat { get; set; }
        public string tinhtrang { get; set; }
        public int matv { get; set; }
        public string ngaygiao { get; set; }
        public double tongthanhtoan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ctdonhang> ctdonhangs { get; set; }
        public virtual thanhvien thanhvien { get; set; }
    }
}
