//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class loaisanpham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public loaisanpham()
        {
            this.sanphams = new HashSet<sanpham>();
        }
    
        public int maloai { get; set; }
        public string tenloai { get; set; }
        public int madm { get; set; }

        public loaisanpham(string tenloai, int madm)
        {
            this.tenloai = tenloai;
            this.madm = madm;
        }

        public loaisanpham(int maloai, string tenloai)
        {
            this.maloai = maloai;
            this.tenloai = tenloai;
        }

        public loaisanpham(int maloai, string tenloai, int madm) : this(maloai, tenloai)
        {
            this.madm = madm;
        }

        public override string ToString()
        {
            return this.maloai + "-" + this.tenloai + "-" +this.madm;
        }

        public virtual danhmuc danhmuc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sanpham> sanphams { get; set; }
    }
}
