//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleWebsite.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BanHangEntity : DbContext
    {
        public BanHangEntity()
            : base("name=BanHangEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ctdonhang> ctdonhangs { get; set; }
        public virtual DbSet<danhgia> danhgias { get; set; }
        public virtual DbSet<danhmuc> danhmucs { get; set; }
        public virtual DbSet<diachi> diachis { get; set; }
        public virtual DbSet<donhang> donhangs { get; set; }
        public virtual DbSet<hinhanh> hinhanhs { get; set; }
        public virtual DbSet<loaisanpham> loaisanphams { get; set; }
        public virtual DbSet<mausac> mausacs { get; set; }
        public virtual DbSet<sanpham> sanphams { get; set; }
        public virtual DbSet<size> sizes { get; set; }
        public virtual DbSet<thanhvien> thanhviens { get; set; }
    }
}
