//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sanpham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sanpham()
        {
            this.ctdonhangs = new HashSet<ctdonhang>();
            this.danhgias = new HashSet<danhgia>();
            this.hinhanhs = new HashSet<hinhanh>();
            this.sizes = new HashSet<size>();
        }
    
        public int masp { get; set; }
        public string tensp { get; set; }
        public double dongia { get; set; }
        public System.DateTime ngaycapnhat { get; set; }
        public string chatlieu { get; set; }
        public string mota { get; set; }
        public int maloai { get; set; }

        public override string ToString()
        {
            return this.masp + "-" + this.tensp;
        }

        public string GetAll()
        {
            return this.masp + "-" + this.tensp + "-" + this.dongia + "-" + 
                this.chatlieu + "-" + this.mota + "-" + this.ngaycapnhat + "-" + this.loaisanpham;
        }

        public sanpham(int masp, string tensp, double dongia, DateTime ngaycapnhat, string chatlieu, string mota, int maloai)
        {
            this.masp = masp;
            this.tensp = tensp;
            this.dongia = dongia;
            this.ngaycapnhat = ngaycapnhat;
            this.chatlieu = chatlieu;
            this.mota = mota;
            this.maloai = maloai;
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ctdonhang> ctdonhangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<danhgia> danhgias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hinhanh> hinhanhs { get; set; }
        public virtual loaisanpham loaisanpham { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<size> sizes { get; set; }
    }
}
