//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class size
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public size()
        {
            this.mausacs = new HashSet<mausac>();
        }
    
        public int masize { get; set; }
        public string size1 { get; set; }
        public int soluong { get; set; }
        public int masp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mausac> mausacs { get; set; }
        public virtual sanpham sanpham { get; set; }

        public override string ToString()
        {
            return this.masize + "-"+this.size1;
        }

        public size(int masize, string size1, int soluong, int masp)
        {
            this.masize = masize;
            this.size1 = size1;
            this.soluong = soluong;
            this.masp = masp;
        }

        public string getAll()
        {
            return this.masize + "-" + this.size1 + "-" +this.soluong+"-"+ this.masp;
        }
    }
}
