//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestFulApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mausac
    {
        public int mamau { get; set; }
        public string tenmau { get; set; }
        public int masize { get; set; }
    
        public virtual size size { get; set; }
    }
}
